var data = [
  {"state": "Alabama", "disease":"ebola", "value": 74},
  {"state": "Alabama", "disease":"flu", "value": 29},
  {"state": "Alaska", "disease":"ebola", "value": 69},
  {"state": "Alaska", "disease":"flu", "value": 18},
  {"state": "Arizona", "disease":"ebola", "value": 59},
  {"state": "Arizona", "disease":"flu", "value": 17},
  {"state": "Arkansas", "disease":"ebola", "value": 78},
  {"state": "Arkansas", "disease":"flu", "value": 34},
  {"state": "California", "disease":"ebola", "value": 54},
  {"state": "California", "disease":"flu", "value": 18},
  {"state": "Colorado", "disease":"ebola", "value": 67},
  {"state": "Colorado", "disease":"flu", "value": 23},
  {"state": "Connecticut", "disease":"ebola", "value": 76},
  {"state": "Connecticut", "disease":"flu", "value": 21},
  {"state": "Delaware", "disease":"ebola", "value": 69},
  {"state": "Delaware", "disease":"flu", "value": 24},
  {"state": "Florida", "disease":"ebola", "value": 61},
  {"state": "Florida", "disease":"flu", "value": 17},
  {"state": "Georgia", "disease":"ebola", "value": 69},
  {"state": "Georgia", "disease":"flu", "value": 22},
  {"state": "Hawaii", "disease":"ebola", "value": 76},
  {"state": "Hawaii", "disease":"flu", "value": 19},
  {"state": "Idaho", "disease":"ebola", "value": 59},
  {"state": "Idaho", "disease":"flu", "value": 21},
  {"state": "Illinois", "disease":"ebola", "value": 72},
  {"state": "Illinois", "disease":"flu", "value": 22},
  {"state": "Indiana", "disease":"ebola", "value": 64},
  {"state": "Indiana", "disease":"flu", "value": 24},
  {"state": "Iowa", "disease":"ebola", "value": 61},
  {"state": "Iowa", "disease":"flu", "value": 24},
  {"state": "Kansas", "disease":"ebola", "value": 73},
  {"state": "Kansas", "disease":"flu", "value": 22},
  {"state": "Kentucky", "disease":"ebola", "value": 69},
  {"state": "Kentucky", "disease":"flu", "value": 30},
  {"state": "Louisiana", "disease":"ebola", "value": 83},
  {"state": "Louisiana", "disease":"flu", "value": 25},
  {"state": "Maine", "disease":"ebola", "value": 68},
  {"state": "Maine", "disease":"flu", "value": 23},
  {"state": "Maryland", "disease":"ebola", "value": 73},
  {"state": "Maryland", "disease":"flu", "value": 24},
  {"state": "Massachusetts", "disease":"ebola", "value": 66},
  {"state": "Massachusetts", "disease":"flu", "value": 21},
  {"state": "Michigan", "disease":"ebola", "value": 70},
  {"state": "Michigan", "disease":"flu", "value": 23},
  {"state": "Minnesota", "disease":"ebola", "value": 63},
  {"state": "Minnesota", "disease":"flu", "value": 24},
  {"state": "Mississippi", "disease":"ebola", "value": 74},
  {"state": "Mississippi", "disease":"flu", "value": 31},
  {"state": "Missouri", "disease":"ebola", "value": 69},
  {"state": "Missouri", "disease":"flu", "value": 24},
  {"state": "Montana", "disease":"ebola", "value": 62},
  {"state": "Montana", "disease":"flu", "value": 22},
  {"state": "Nebraska", "disease":"ebola", "value": 57},
  {"state": "Nebraska", "disease":"flu", "value": 23},
  {"state": "Nevada", "disease":"ebola", "value": 64},
  {"state": "Nevada", "disease":"flu", "value": 17},
  {"state": "New Hampshire", "disease":"ebola", "value": 63},
  {"state": "New Hampshire", "disease":"flu", "value": 23},
  {"state": "New Jersey", "disease":"ebola", "value": 70},
  {"state": "New Jersey", "disease":"flu", "value": 20},
  {"state": "New Mexico", "disease":"ebola", "value": 64},
  {"state": "New Mexico", "disease":"flu", "value": 21},
  {"state": "New York", "disease":"ebola", "value": 68},
  {"state": "New York", "disease":"flu", "value": 21},
  {"state": "North Carolina", "disease":"ebola", "value": 64},
  {"state": "North Carolina", "disease":"flu", "value": 26},
  {"state": "North Dakota", "disease":"ebola", "value": 64},
  {"state": "North Dakota", "disease":"flu", "value": 26},
  {"state": "Ohio", "disease":"ebola", "value": 72},
  {"state": "Ohio", "disease":"flu", "value": 24},
  {"state": "Oklahoma", "disease":"ebola", "value": 100},
  {"state": "Oklahoma", "disease":"flu", "value": 27},
  {"state": "Oregon", "disease":"ebola", "value": 36},
  {"state": "Oregon", "disease":"flu", "value": 12},
  {"state": "Pennsylvania", "disease":"ebola", "value": 55},
  {"state": "Pennsylvania", "disease":"flu", "value": 24},
  {"state": "Rhode Island", "disease":"ebola", "value": 66},
  {"state": "Rhode Island", "disease":"flu", "value": 22},
  {"state": "South Carolina", "disease":"ebola", "value": 65},
  {"state": "South Carolina", "disease":"flu", "value": 28},
  {"state": "South Dakota", "disease":"ebola", "value": 69},
  {"state": "South Dakota", "disease":"flu", "value": 25},
  {"state": "Tennessee", "disease":"ebola", "value": 59},
  {"state": "Tennessee", "disease":"flu", "value": 30},
  {"state": "Texas", "disease":"ebola", "value": 93},
  {"state": "Texas", "disease":"flu", "value": 22},
  {"state": "Utah", "disease":"ebola", "value": 49},
  {"state": "Utah", "disease":"flu", "value": 20},
  {"state": "Vermont", "disease":"ebola", "value": 61},
  {"state": "Vermont", "disease":"flu", "value": 21},
  {"state": "Virginia", "disease":"ebola", "42": 23},
  {"state": "Virginia", "disease":"flu", "17": 21},
  {"state": "Washington", "disease":"ebola", "value": 60},
  {"state": "Washington", "disease":"flu", "value": 21},
  {"state": "West Virginia", "disease":"ebola", "value": 69},
  {"state": "West Virginia", "disease":"flu", "value": 30},
  {"state": "Wisconsin", "disease":"ebola", "value": 62},
  {"state": "Wisconsin", "disease":"flu", "value": 23},
  {"state": "Wyoming", "disease":"ebola", "value": 63},
  {"state": "Wyoming", "disease":"flu", "value": 24}]

var visualization = d3plus.viz()
    .container("#svg_ebola_flu_bar")
    .data(data)
    .type("bar")
    .id("disease")
    .x("state")
    .y({"stacked": true, "value": "value"})
    .title("Ebola vs. Flu (Oct 2014 - March 2015)")
    .footer({"font":{"size":"20px"},"value":"This stacked bar chart highlights how often audiences searched for the flu as opposed to Ebola. Overwhelmingly, audiences searched for Ebola."})
    .tooltip("state")
    .draw()


    